name: 'OpenCommitX — improve commits with AI 🧙'
description: 'Fork of OpenCommit (https://github.com/di-sukharev/opencommit) that replaces lame commit messages with meaningful AI-generated messages when you push to remote + some additional features and configurability.'
author: 'https://github.com/xwberry'
branding:
  icon: 'git-commit'
  color: 'green'
keywords:
  [
    'git',
    'chatgpt',
    'gpt',
    'ai',
    'openai',
    'opencommit',
    'aicommit',
    'aicommits',
    'gptcommit',
    'commit'
  ]

inputs:
  GITHUB_TOKEN:
    description: 'GitHub token'
    required: true

runs:
  using: 'node24'
  main: 'out/github-action.cjs'
