[workspace]
authors = ["xberry1231 <xander.berry13@gmail.com>"]
channels = ["conda-forge"]
name = "opencommitx"
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.11,<3.15"
